# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUM_MEUruyyj_D3Jn7yuPljiMZqIXj-P
"""


import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix


df = pd.read_csv("/content/mental_health_1000_synthetic_dataset.csv")

print("Dataset Loaded Successfully!")
print(df.head())


df = df.drop(columns=["participant_id"])

categorical_cols = [
    "gender",
    "occupation",
    "sleep_regularity",
    "physical_activity_level",
    "social_interaction_frequency",
    "phone_usage_affects_mood",
    "risk_label"
]

label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le


X = df.drop(columns=["risk_label"])
y = df["risk_label"]



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

log_pred = log_model.predict(X_test_scaled)

print("\n===== Logistic Regression Results =====")
print("Accuracy:", accuracy_score(y_test, log_pred))
print("F1 Score:", f1_score(y_test, log_pred, average="macro"))


rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("\n===== Random Forest Results =====")
print("Accuracy:", accuracy_score(y_test, rf_pred))
print("F1 Score:", f1_score(y_test, rf_pred, average="macro"))


feature_importances = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nTop Important Features:")
print(feature_importances.head(10))


joblib.dump(rf_model, "mental_health_rf_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("\n✅ Model Saved Successfully!")



from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np
import pandas as pd

app = FastAPI(title="Mental Health Risk Prediction API")

# Load model and scaler
model = joblib.load("/content/mental_health_rf_model.pkl")
scaler = joblib.load("/content/scaler.pkl")

# Define input schema
class PredictionInput(BaseModel):
    age: int
    gender: int
    occupation: int
    phq1_interest: int
    phq2_depressed: int
    phq3_sleep: int
    phq4_energy: int
    phq5_appetite: int
    phq6_failure: int
    phq7_concentration: int
    phq8_movement: int
    phq9_suicidal: int
    avg_daily_screen_time_hours: float
    late_night_usage_hours: float
    sleep_duration_hours: float
    sleep_regularity: int
    physical_activity_level: int
    social_media_usage_hours: float
    entertainment_usage_hours: float
    social_interaction_frequency: int
    phone_usage_affects_mood: int

@app.post("/predict")
def predict(data: PredictionInput):

    input_dict = data.dict()
    input_df = pd.DataFrame([input_dict])

    # Scale input
    input_scaled = scaler.transform(input_df)

    prediction = model.predict(input_scaled)[0]
    probabilities = model.predict_proba(input_scaled)[0]

    confidence = round(np.max(probabilities) * 100, 2)

    return {
        "predicted_risk_level": int(prediction),
        "confidence_percentage": confidence
    }

joblib.dump(label_encoders, "label_encoders.pkl")

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

# ===============================
# Initialize FastAPI App
# ===============================
app = FastAPI(title="Mental Health Risk Prediction API")

# ===============================
# Load Trained Model & Encoders
# ===============================
model = joblib.load("/content/mental_health_rf_model.pkl")
label_encoders = joblib.load("/content/label_encoders.pkl")

# ===============================
# Input Schema (Must match training features)
# ===============================
class MentalHealthInput(BaseModel):
    age: int
    gender: str
    occupation: str
    phq1: int
    phq2: int
    phq3: int
    phq4: int
    phq5: int
    phq6: int
    phq7: int
    phq8: int
    phq9: int
    average_daily_screen_time: float
    late_night_phone_usage: float
    sleep_duration: float
    sleep_regularity: str
    physical_activity_level: str
    social_media_usage: float
    entertainment_usage: float
    social_interaction_frequency: str
    phone_usage_affects_mood: str


# ===============================
# Health Check Endpoint
# ===============================
@app.get("/")
def home():
    return {"message": "Mental Health Risk Prediction API is Running"}


# ===============================
# Prediction Endpoint
# ===============================
@app.post("/predict")
def predict(data: MentalHealthInput):

    input_dict = data.dict()

    # Encode categorical features
    categorical_features = [
        "gender",
        "occupation",
        "sleep_regularity",
        "physical_activity_level",
        "social_interaction_frequency",
        "phone_usage_affects_mood"
    ]

    for feature in categorical_features:
        encoder = label_encoders[feature]
        input_dict[feature] = encoder.transform([input_dict[feature]])[0]

    # Convert to numpy array (order must match training)
    input_array = np.array(list(input_dict.values())).reshape(1, -1)

    # Make prediction (NO scaling)
    prediction = model.predict(input_array)[0]
    probabilities = model.predict_proba(input_array)[0]
    confidence = round(max(probabilities) * 100, 2)

    # Convert numeric prediction to readable label
    risk_mapping = {0: "Low", 1: "Moderate", 2: "High"}
    risk_label = risk_mapping[prediction]

    return {
        "predicted_risk_level": risk_label,
        "confidence_percentage": confidence
    }


# ===============================
# Render Deployment Config
# ===============================
import uvicorn

